### ISSUE TITLE
Issue while executing "npm start"

### ISSUE THREAD

**Issue by RahulChandrashekar17061984** [wiseman/ar-drone-rest#1]
Hi,

I have installed the latest build from node-ar-drone (version 3.3) and when i execute ar-drone-rest 

--> npm start

i get the below exception

D:\parrot_drone\ar-drone-rest-master>npm start

> ar-drone-rest@0.0.1 start D:\parrot_drone\ar-drone-rest-master
> node server.js

module.js:471
    throw err;
    ^

Error: Cannot find module 'ar-drone'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\parrot_drone\ar-drone-rest-master\lib\server.js:1:77)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\ParrotDrone\\nodejs\\node.exe" "D:\\ParrotDrone\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! ar-drone-rest@0.0.1 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ar-drone-rest@0.0.1 start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ar-drone-rest package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ar-drone-rest
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ar-drone-rest
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     D:\parrot_drone\ar-drone-rest-master\npm-debug.log

**Comment by RahulChandrashekar17061984** [comment]
This issue is closed.
It is due to the install dependency issue.
